Feat/update features
alercebroker/alerce-scribe pull request #31
Opened 2023-04-21 13:57 UTC by AlxEnashi

2023-04-21 18:47 UTC, pcastelln approved these changes

2023-04-21 20:11 UTC, pgallardor commented on mongo_scribe/command/exceptions.py
> +class NoFearuteVersionProvidedException(ValueError):
Typo
```suggestion
class NoFeatureVersionProvidedException(ValueError):
```

2023-04-21 20:11 UTC, pgallardor commented on mongo_scribe/command/commands.py
> +        self.features_version = data.pop("features_version")
```suggestion
    def _check_inputs(self, collection, data, criteria):
        super()._check_inputs(collection, data, criteria)
        if "features_version" not in data:
            raise NoFeatureVersionProvidedException()
        self.features_version = data.pop("features_version")
```

2023-04-21 20:11 UTC, pgallardor commented on mongo_scribe/command/commands.py
> +            **self.criteria,
Me puedes explicar mas o menos cuál es la idea de este criterio extra?

2023-04-21 20:53 UTC, AlxEnashi commented on mongo_scribe/command/commands.py
> +            **self.criteria,
solo ejecuta el update si encuentra una feature que cumpla con el criterio de aid del objeto y que si versio no este guardada, pero deberia ser la version y el nombre, y quizas el fid? es el criterio para insertar solamente no updates no replaces.

2023-04-21 20:58 UTC, AlxEnashi commented on mongo_scribe/command/commands.py
> +            **self.criteria,
ups, pero esta malo creo... xq features version es parte de cada feature y features del objeto es una lista..  a menos que ese pueda hacerse con un "any" no funcionara... voy a revisar como hacerlo bien

2023-04-24 13:53 UTC, pcastelln commented on mongo_scribe/command/commands.py
> +            **self.criteria,
En probabilidades se busca por nombre de calsificador y versión. La cosa es que asume que para el clasificador dado vas a querer hacer un insert de todas a la vez o nada. Creo que lo más sano es que asumamos lo mismo para las features. Si la versión es distinta podemos tirar más o menos cosas, pero un clasificador con una versión dada siempre tiene que usar los mismos features

2023-04-24 13:55 UTC, pcastelln requested changes

2023-04-24 13:55 UTC, pcastelln commented on mongo_scribe/command/commands.py
> +                "fid": feature["fid"],
basado en el esquema actual, en la base de datos debería ir como `version`, `name` y `value`

2023-04-24 13:55 UTC, pcastelln commented on mongo_scribe/command/commands.py
> +                    "features.$[el].feature_value": feature["value"],
Lo mismo que el comentario anterior

2023-04-26 15:13 UTC, pcastelln approved these changes

2023-04-26 15:15 UTC, merged